(function (global) {
  const ns = (global.VideoEditorModules = global.VideoEditorModules || {});

  ns.createAppInitialState = function createAppInitialState() {
    return {
    // ── 全局状态 ────────────────────────────────────────────────
    loading:     true,
    apiSessionToken: "",
    apiCsrfToken: "",
    apiSessionRequired: false,
    apiSessionReady: false,
    projectDir:  "",
    videosDir:   "",
    currentStep: 0,   // 服务器工作流进度（只读，不被导航操作修改）
    activePanel: 0,   // 当前显示的面板（由导航操作控制）
    steps:       [],
    config:      {},
    topModule:   "analysis",      // analysis | production
    productionView: "hub",        // hub | workflow

    // ── 全局素材库（语义分析模块）──────────────────────────────
    libraryStats: {
      total_assets: 0,
      video_assets: 0,
      image_assets: 0,
      total_locations: 0,
      available_assets: 0,
      local_assets: 0,
      gdrive_assets: 0,
      semantic_dimensions_supported: 0,
      semantic_ready_assets: 0,
      semantic_pending_assets: 0,
      embedding_ready_assets: 0,
      embedding_pending_assets: 0,
      hybrid_search_enabled: false,
      embedding_enabled: false,
    },
    libraryQuery:     "",
    libraryResults:   [],
    libraryLoading:   false,
    libraryMessage:   "",
    libraryPageSize:  120,
    libraryOffset:    0,
    libraryTotalMatches: 0,
    libraryHasMore:   false,
    librarySearchMode: "hybrid", // hybrid | keyword | vector
    libraryMediaType: "all", // all | video | image
    libraryRetrievalMode: "browse",
    libraryLastMode: "hybrid",
    libraryLastMediaType: "all",
    libraryHybridEnabled: false,
    libraryEmbeddingEnabled: false,
    libraryEmbeddingReadyAssets: 0,
    libraryEmbeddingStatus: "",
    libraryEmbeddingStatusMessage: "",
    libraryVisualSearchEnabled: false,
    libraryVisualEmbeddingsCount: 0,
    ingestLocalPath:  "",
    ingestLocalMaxVideos: 600,
    ingestLocalPreviewLoading: false,
    ingestLocalPreviewError: "",
    ingestLocalPreview: null,
    ingestImagePath:  "",
    ingestImageMaxItems: 1200,
    ingestImagePreviewLoading: false,
    ingestImagePreviewError: "",
    ingestImagePreview: null,
    ingestDriveUrl:   "",
    ingestDriveMaxVideos: 500,
    ingestDrivePriority: "",
    ingestDriveMaxScanFolders: 120,
    ingestDriveImageUrl: "",
    ingestDriveImageMaxItems: 1200,
    ingestDriveImagePriority: "",
    ingestDriveImageMaxScanFolders: 120,
    ingestImageDrivePreviewLoading: false,
    ingestImageDrivePreviewError: "",
    ingestImageDrivePreview: null,
    ingestPreviewLoading: false,
    ingestPreviewError: "",
    ingestPreview: null,
    ingestLoading:    false,
    ingestMessage:    "",
    ingestJobId:      "",
    ingestProgress:   0,
    ingestLog:        [],
    ingestRefresh:    false,
    aiSettings: {
      provider: "openai",
      ai_model: "",
      embedding_model: "",
      ai_base_url: "",
      openai_api_key: "",
      anthropic_api_key: "",
      clear_openai_api_key: false,
      clear_anthropic_api_key: false,
    },
    aiCatalog: {
      default_provider: "openai",
      default_embedding_model: "text-embedding-3-small",
      providers: [
        {
          provider_id: "openai",
          label: "OpenAI",
          default_base_url: "https://api.openai.com/v1",
          models: ["gpt-4o-mini", "gpt-4o", "gpt-4.1-mini", "o4-mini", "o3-mini"],
          embedding_models: ["text-embedding-3-small", "text-embedding-3-large", "text-embedding-ada-002"],
        },
        {
          provider_id: "anthropic",
          label: "Anthropic",
          default_base_url: "https://api.anthropic.com",
          models: ["claude-sonnet-4-6", "claude-3-7-sonnet-latest", "claude-3-5-haiku-latest"],
          embedding_models: [],
        },
        {
          provider_id: "moonshot",
          label: "Moonshot / Kimi",
          default_base_url: "https://api.moonshot.cn/v1",
          models: ["moonshot-v1-8k", "moonshot-v1-32k", "moonshot-v1-128k"],
          embedding_models: [],
        },
        {
          provider_id: "qwen",
          label: "Qwen",
          default_base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1",
          models: ["qwen-plus", "qwen-turbo", "qwen-max"],
          embedding_models: [],
        },
        {
          provider_id: "gemini",
          label: "Gemini",
          default_base_url: "https://generativelanguage.googleapis.com/v1beta/openai",
          models: ["gemini-2.0-flash", "gemini-1.5-pro", "gemini-1.5-flash"],
          embedding_models: [],
        },
        {
          provider_id: "maxmini",
          label: "MiniMax",
          default_base_url: "https://api.minimax.chat/v1",
          models: ["abab6.5s-chat", "abab6.5t-chat", "abab6.5g-chat"],
          embedding_models: [],
        },
      ],
    },
    aiStatus: {
      openai_api_key_set: false,
      anthropic_api_key_set: false,
      openai_api_key_masked: "",
      anthropic_api_key_masked: "",
      secret_storage: {
        backend: "",
        available: false,
        reason: "",
      },
    },
    aiLoading: false,
    aiSaving:  false,
    aiMessage: "",
    uiSettings: {
      onboarding_completed: false,
      creator_mode: true,
      font_scale: 1.0,
      preferred_production_view: "hub",
      default_videos_dir: "",
      default_project_dir: "",
      auto_open_last_project: true,
      last_project_dir: "",
    },
    uiSettingsLoading: false,
    uiSettingsSaving: false,
    uiSettingsMessage: "",
    showOnboardingWizard: false,
    preflightLoading: false,
    preflightMessage: "",
    preflightReport: null,
    preflightLastRunAt: "",

    // ── 制作模块 Step 1：素材选择（最多 50）────────────────────
    selectedAssets:       [],
    maxSelectedAssets:    50,
    selectionLoading:     false,
    selectionError:       "",
    productionProjectDir: "",

    // ── 新建/打开项目对话框 ─────────────────────────────────────
    showInit:      false,
    initMode:      "new",          // "new" | "open"
    initVideosDir: "",
    initProjectDir: "",
    initOpenDir:   "",
    initLoading:   false,
    initError:     "",

    // ── 当前选题（Step 2）──────────────────────────────────────
    topics:         [],
    selectedTopic:  null,
    topicCustom:    "",

    // ── 脚本（Step 3）──────────────────────────────────────────
    scriptClips:  [],
    scriptSubs:   [],
    scriptJson:   "",
    scriptView:   "visual",        // "visual" | "json"
    scriptSaving: false,

    // ── 帧预览（Step 5）────────────────────────────────────────
    frames: [],

    // ── 三轨时间线（R7）────────────────────────────────────────
    timelineTracks: { video: [], subtitle: [], audio: [] },
    timelineView: "multi",  // "multi" | "legacy"
    timelineDragIdx: -1,
    timelineDragTrack: "",
    timelineSubtitleLink: "contained",  // "contained" | "overlap" | "none"

    // ── 粗剪视频（Step 6）──────────────────────────────────────
    beautyPreview: { show: false, original: null, result: null, processing_ms: 0 },
    roughUrl:   "",
    renderOpts: {
      width: 1080, height: 1920, fps: 30, crf: 18, preset: "medium",
      enable_skin_smooth: true, enable_color_grading: true,
      enable_skill_enhance: true,
      aesthetic_preset: "travel_story",
      transition_style: "fade",
      transition_duration: 0.35,
      rough_target_seconds: 15,
      rough_max_clips: 8,
      rough_merge_gap_s: 0.15,
      rough_remove_phrases: "嗯,啊,然后,就是,那个",
      skin_smooth_strength: 0.4,
      beauty_lut: '',
      beauty_region_graded: true,
      bgm_path: "", bgm_volume: 0.35, narration_path: "",
      subtitle_font: "PingFangSC-Regular", subtitle_size: 56,
    },

    // ── 精渲染（Step 7）────────────────────────────────────────
    stageFiles:  {},
    finalUrl:    "",
    stageNames: [
      "片段剪切 & 合并",
      "美颜滤镜",
      "色彩调级",
      "字幕压制",
      "BGM 混音",
    ],

    // ── 能力工作台（Capability）──────────────────────────────────
    capabilityTab: "topic_library",
    capabilityMessage: "",
    capabilityMessageType: "info",
    capabilityGroups: [
      {
        key: "creative",
        title: "创作链路",
        items: [
          { tab: "topic_library", label: "选题库", hint: "模板库与素材初始化", mode: "project" },
          { tab: "topic_copy", label: "选题+文案", hint: "选题映射文案草稿", mode: "project" },
          { tab: "text_rough", label: "文字粗剪", hint: "句级删减与时长控制", mode: "project" },
          { tab: "short_clip", label: "短视频快剪", hint: "精华片段快速规划", mode: "project" },
          { tab: "refinement", label: "视频精剪", hint: "NLE 交接与导回", mode: "project" },
          { tab: "audio_voice", label: "配乐配音", hint: "旁白/BGM/混音", mode: "project" },
        ],
      },
      {
        key: "semantics",
        title: "语义与文案",
        items: [
          { tab: "subtitle_calibration", label: "字幕校准", hint: "中英文+时间轴", mode: "hybrid" },
          { tab: "image_semantic", label: "图片语义", hint: "图像分析与语义检索", mode: "hybrid" },
          { tab: "article_expand", label: "公众号扩写", hint: "文章结构化扩写", mode: "hybrid" },
          { tab: "publish_prep", label: "发布文案", hint: "分平台标题/描述/关键词", mode: "hybrid" },
        ],
      },
      {
        key: "distribution",
        title: "分发与发布",
        items: [
          { tab: "social_export", label: "社媒导出", hint: "多平台规格导出", mode: "hybrid" },
          { tab: "content_publish", label: "内容发布", hint: "跨平台发布执行", mode: "hybrid" },
        ],
      },
      {
        key: "automation",
        title: "自动化与治理",
        items: [
          { tab: "workflow_builder", label: "自定义工作流", hint: "节点编排与重跑", mode: "hybrid" },
          { tab: "idempotency_cache", label: "幂等缓存", hint: "去重与重试治理", mode: "hybrid" },
          { tab: "agent_templates", label: "Agent 模板", hint: "技能模板与变量", mode: "hybrid" },
          { tab: "agent_observability", label: "Agent 观测", hint: "成本/失败/重放", mode: "hybrid" },
        ],
      },
    ],
    capabilities: [],
    capabilityStatuses: {},
    capabilitiesLoading: false,
    topicLibraryLoading: false,
    topicLibraryQuery: "",
    topicLibraryCategory: "",
    topicLibraryItems: [],
    topicForm: {
      slug: "",
      title: "",
      category: "travel",
      audience: "short_video",
      hook_style: "story",
      outline_template: "",
      tags: "",
    },
    topicCopy: {
      slug: "",
      target_duration_s: 60,
      draft: null,
    },
    textRoughInput: {
      removed_phrases: "嗯,啊,然后,就是,那个",
      target_duration_s: 15,
      merge_gap_s: 0.15,
      keep_span_indexes: "",
      drop_span_indexes: "",
      apply_removed_phrases: true,
    },
    textRoughSpans: [],
    textRoughFilterKeyword: "",
    textRoughSourceLoading: false,
    textRoughSourceError: "",
    textRoughPlan: null,
    shortClipInput: {
      target_duration_s: 30,
      max_clips: 8,
    },
    shortClipPlan: null,
    refineInput: {
      style: "travel_story",
      editor: "internal_ffmpeg",
      quality: "high",
    },
    refinePlan: null,
    handoffInput: {
      editor: "finalcut",
      title: "VideoEditer Timeline",
      fps: 30,
      launch: true,
      app_name: "",
      master_source: "",
      output_name: "final.mp4",
      copy_mode: "copy",
    },
    handoffResult: null,
    handoffLaunchResult: null,
    handoffCollectResult: null,
    nleConnectors: [],
    nleConnectorsLoading: false,
    socialExportInput: {
      input_video: "",
      platforms: "tiktok短视频,微信短视频,抖音短视频,小红书短视频,微信公众号,b站视频,YouTube视频",
      quality: "high",
      output_dir: "",
      strict_duration_limit: true,
    },
    socialExportPlan: null,
    socialExportValidation: null,
    socialExportResult: null,
    socialExportRunning: false,
    socialExportProgress: 0,
    socialExportLog: [],
    socialExportJobId: "",
    socialExportHistory: [],
    socialExportHistoryLoading: false,
    exportProfiles: [],
    customExportTemplates: [],
    socialTemplateForm: {
      platform_id: "",
      name: "",
      width: 1080,
      height: 1920,
      fps: 30,
      video_bitrate: "10M",
      audio_bitrate: "192k",
      max_duration_s: 180,
    },
    subtitleInput: {
      input_mode: "project",
      mode: "timeline_align",
      translation: "off",
      source_audio: "",
      use_llm: false,
      llm_provider: "",
      llm_model: "",
      subtitles_json: "[]",
    },
    subtitlePlan: null,
    subtitleResult: null,
    imageSemanticInput: {
      input_mode: "inline",
      image_paths: "",
      query: "",
      limit: 30,
      analyze_max_images: 1200,
      retrieval_mode: "hybrid",
      auto_ingest: true,
    },
    imageSemanticAnalyze: null,
    imageSemanticSearch: null,
    imageSemanticAiStatus: null,
    articleExpandInput: {
      input_mode: "inline",
      source_text: "",
      key_points: "",
      tone: "professional",
      length_target: 1200,
      title_count: 5,
      use_llm: false,
      llm_provider: "",
      llm_model: "",
    },
    articleExpandResult: null,
    publishPrepInput: {
      input_mode: "inline",
      script_text: "",
      voiceover_text: "",
      platforms: "xiaohongshu,ixigua,douyin,wechat_channels,wechat_mp,youtube,instagram,twitter,threads,facebook,blog",
      platform_content_type: "video_post",
      use_saved_profiles: true,
      use_llm: false,
      llm_provider: "",
      llm_model: "",
      profile_overrides_json: "{}",
    },
    publishPrepProfiles: [],
    publishPrepResult: null,
    contentPublishInput: {
      input_mode: "project",
      platforms: "xiaohongshu,ixigua,douyin,wechat_channels,wechat_mp,youtube,instagram,twitter,threads,facebook,blog",
      platform_content_type: "video_post",
      dry_run: true,
      session_id: "",
      authenticated: false,
      expires_in_minutes: 120,
      title: "",
      description: "",
      keywords: "",
      media_urls: "",
      article_markdown: "",
      article_html: "",
      connectors_json: "{}",
    },
    publishConnectorEditorMode: "form", // form | json
    publishConnectorRows: [],
    publishSettingsLoading: false,
    publishSettingsSaving: false,
    publishSettingsMessage: "",
    contentPublishPlatforms: [],
    contentPublishSession: null,
    contentPublishPlan: null,
    contentPublishRun: null,
    publishRecoveryHint: null,
    showPublishFailureModal: false,
    workflowCatalog: [],
    workflowList: [],
    workflowRuns: [],
    workflowRunsTotal: 0,
    workflowPlan: null,
    workflowRunResult: null,
    workflowRunning: false,
    workflowRunJobId: "",
    workflowHistoryLoading: false,
    workflowBuilder: {
      workflow_id: "",
      name: "自定义工作流",
      description: "",
      start_step_id: "",
      dry_run: true,
      run_inline: false,
      steps_json: `[
  {
    "step_id": "step_subtitle",
    "capability_id": "subtitle_calibration",
    "action": "run",
    "input_mode": "inline",
    "input": {
      "input_mode": "inline",
      "mode": "text_only",
      "translation": "off",
      "subtitles": [
        {"index": 1, "start_time": 0.0, "end_time": 1.2, "cn_text": "示例字幕一"},
        {"index": 2, "start_time": 1.3, "end_time": 2.5, "cn_text": "示例字幕二"}
      ]
    }
  },
  {
    "step_id": "step_publish_copy",
    "capability_id": "publish_prep",
    "action": "generate",
    "input_mode": "inline",
    "input": {
      "input_mode": "inline",
      "platforms": ["douyin", "youtube"],
      "script_text": "标题参考：{{steps.step_subtitle.response.result.quality_report.total_subtitles}}条字幕",
      "voiceover_text": "这里可以拼接上一步输出"
    }
      }
]`,
      input_json: "{}",
    },
    workflowSteps: [],
    workflowStepJsonError: "",
    workflowQuickAddCapability: "",
    workflowCanvasDragIndex: -1,
    workflowCanvasDropIndex: -1,
    workflowCanvasNodeDragOffsetX: 0,
    workflowCanvasNodeDragOffsetY: 0,
    workflowCanvasPointerBound: false,
    workflowCanvasPointerMoveHandler: null,
    workflowCanvasPointerUpHandler: null,
    workflowShortcutBound: false,
    workflowShortcutKeydownHandler: null,
    workflowCanvasLinkActive: false,
    workflowCanvasLinkFromIndex: -1,
    workflowCanvasLinkOutputKey: "",
    workflowCanvasLinkPointerX: 0,
    workflowCanvasLinkPointerY: 0,
    workflowCanvasZoom: 1,
    workflowCanvasPanX: 20,
    workflowCanvasPanY: 20,
    workflowCanvasPanning: false,
    workflowCanvasPanStartClientX: 0,
    workflowCanvasPanStartClientY: 0,
    workflowCanvasPanStartX: 0,
    workflowCanvasPanStartY: 0,
    workflowCanvasSize: { width: 1200, height: 560 },
    workflowUndoStack: [],
    workflowRedoStack: [],
    workflowHistoryMuted: false,
    workflowHistoryMax: 120,
    workflowClipboardNode: null,
    workflowRuntimeStatusMap: {},
    workflowRuntimeRunningStepId: "",
    workflowRuntimeLastRunId: "",
    workflowActiveStepIndex: 0,
    workflowSimpleMode: true,
    audioInput: {
      mood: "travel_story",
      provider: "elevenlabs",
      voice_id: "",
      api_key: "",
      model_id: "eleven_multilingual_v2",
      output_dir: "",
      dry_run: true,
      timeline_output: "",
      master_input: "",
      bgm_audio: "",
      auto_pick_bgm: true,
      bgm_library_dir: "",
      bgm_provider: "local_library",
      bgm_endpoint: "",
      bgm_api_key: "",
      bgm_download: true,
      bgm_cache_enabled: true,
      bgm_strict_schema: false,
      bgm_force_refresh: false,
      bgm_cache_max_age_days: 0,
      bgm_loop: true,
      bgm_fade_out_s: 2.0,
      mix_output: "",
      replace_master: true,
      origin_volume: 0.8,
      narration_volume: 1.0,
      bgm_volume: 0.25,
      enable_ducking: true,
      ducking_threshold: 0.03,
      ducking_ratio: 8.0,
      ducking_attack_ms: 15,
      ducking_release_ms: 250,
    },
    audioPlan: null,
    audioSynthesis: null,
    audioTimeline: null,
    audioMixResult: null,
    audioBgmPick: null,
    audioPipelineRunning: false,
    audioPipelineProgress: 0,
    audioPipelineJobId: "",
    audioPipelineResult: null,
    idempotencyCacheInput: {
      source: "merged",
      ttl_seconds: 7 * 24 * 3600,
      include_expired: false,
      limit: 200,
      offset: 0,
      actor_id: "",
      endpoint: "",
      idempotency_key: "",
      project_path: "",
      match_mode: "contains",
    },
    idempotencyCacheLoading: false,
    idempotencyCachePruning: false,
    idempotencyCacheRecords: [],
    idempotencyCacheStats: null,
    idempotencyCacheLastPrune: null,
    idempotencyPruneInput: {
      ttl_seconds: 7 * 24 * 3600,
      remove_expired: true,
      clear_memory: false,
      clear_persisted: false,
      max_entries: "",
    },
    agentObservabilityInput: {
      actor_id: "",
      limit: 200,
      top_n: 5,
      include_items: true,
      status: "",
      task_mode: "",
      capability_id: "",
      skill_id: "",
      replay_supported: "",
      since: "",
      until: "",
    },
    agentObservabilityLoading: false,
    agentObservabilitySummary: null,
    agentObservabilityItems: [],
    agentObservabilityItemsTotal: 0,
    agentObservabilityItemsOffset: 0,
    agentObservabilityItemsHasMore: false,
    agentObservabilityHistoryCount: 0,
    agentObservabilityWindowCount: 0,
    agentObservabilityWindowLimit: 200,
    agentObservabilityExporting: "",
    agentObservabilityLastExport: "",
    agentReplayRunningJobId: "",
    agentTaskDetailJobId: "",
    agentTaskDetailLoading: false,
    agentTaskDetailError: "",
    agentTaskDetail: null,
    agentTaskDetailLastExport: "",
    agentTemplateFilters: {
      capability_id: "",
      scope: "",
      actor_id: "",
      include_system: true,
      resolve: true,
    },
    agentTemplateSearch: "",
    agentTemplatesLoading: false,
    agentTemplates: [],
    agentTemplateSelectedKeys: [],
    agentTemplateBulk: {
      target: "overrides",
      key: "",
      value: "",
      parse_json: false,
    },
    agentTemplateEditor: {
      template_id: "",
      name: "",
      capability_id: "",
      scope: "project",
      actor_id: "",
      tags: "",
      base_template_id: "",
      content_json: "{}",
      overrides_json: "{}",
      variables_json: "[]",
    },

    // ── 后台任务 ────────────────────────────────────────────────
    jobId:       null,
    jobStatus:   "",               // running | done | error
    jobLog:      [],
    jobTimer:    null,
    jobProgress: 0,
    jobEta: {
      available: false,
      remaining_seconds: null,
      source: "none",
      confidence: 0,
    },
    systemLoad: {
      cpu_count: 0,
      load_1m: 0,
      load_5m: 0,
      load_15m: 0,
      load_ratio_1m: 0,
    },
    runningHeavyJobs: [],
    taskQueue: {
      max_running: 1,
      running_count: 0,
      queued_count: 0,
      running: [],
      queued: [],
    },
    taskQueueTimer: null,

    // ── 素材列表（Step 1）──────────────────────────────────────
    materials:   {},

    // ── 任务恢复信息（S2）───────────────────────────────────────
    jobRecovery: null,

    // ── Toast 通知 ──────────────────────────────────────────────
    toasts: [],

    };
  };
})(window);
